spring:
  datasource:
    url: jdbc:postgresql://{$DB_HOST:prod-db}:{DB_PORT:5433}/rides
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  kafka:
    # Brokers which the client will connect with via TCP to initialise Kafka
    # Sends a MetadataRequest to the broker to obtain cluster metadata
    # e.g. brokers in cluster, partition leaders, replicas, controller
    # After obtaining the metadata, it will disconnect from the bootstrap server and
    # depending on if the client is producing/consuming, it will connect directly with the partition leader for the topic
    bootstrap-servers: {$KAFKA_BOOTSTRAP_SERVERS}

logging:
  level:
    root: INFO
    com.zaxxer.hikari: INFO
    org.flywaydb.core.internal.command.DbMigrate: INFO